### ISSUE TITLE
Exception: Could not instantiate image codec

### ISSUE THREAD

**Issue by eug48** [snapfeed/snapfeed-sdk#9]
Thanks, the beta looks great overall!

There appears to be a bug when I click on Navigate but don't draw anything prior to clicking Send. 

E/flutter ( 8307): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: Could not instantiate image codec.
E/flutter ( 8307): 0      _futurize (dart:ui/painting.dart:4304:5)
E/flutter ( 8307): 1      instantiateImageCodec (dart:ui/painting.dart:1682:10)
E/flutter ( 8307): 2      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:88:12)
E/flutter ( 8307): 3      FeedbackSketcherState.getSketch (package:snapfeed/src/feedback/sketcher/sketcher.dart:156:40)
E/flutter ( 8307): 4      SnapfeedState._sendFeedback (package:snapfeed/src/snapfeed_widget.dart:305:56)
E/flutter ( 8307): 5      _FeedbackCardContentState.build.<anonymous closure> (package:snapfeed/src/feedback/feedback_card_content.dart:95:26)
E/flutter ( 8307): 6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter ( 8307): 7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)

_screenshotData is null

**Comment by mhmoudsabry** [comment]
i got an error look like yours 

> I/flutter (20430): #238    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (20430): #239    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (20430): #240    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (20430): #244    _invoke (dart:ui/hooks.dart:259:10)
I/flutter (20430): #245    _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (20430): (elided 6 frames from package dart:async)
I/flutter (20430):
I/flutter (20430): Path:
I/flutter (20430): /data/user/0/com.appsvalley.almaktabapp/app_flutter/files/6850c200-a8a8-4f8f-bc09-8738f16ccc73.pdf
I/flutter (20430): ════════════════════════════════════════════════════════════════════════════════════════════════════
